//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/enviarlot" +
            "eeventos/WsEnviarLoteEventos.svc")]
        public string WebServices_WsEnviarRestrira_ServicoEnviarLoteEventos {
            get {
                return ((string)(this["WebServices_WsEnviarRestrira_ServicoEnviarLoteEventos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.envio.esocial.gov.br/servicos/empregador/enviarloteeventos/Ws" +
            "EnviarLoteEventos.svc")]
        public string WebServices_WsEnviarProducao_ServicoEnviarLoteEventos {
            get {
                return ((string)(this["WebServices_WsEnviarProducao_ServicoEnviarLoteEventos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.consulta.esocial.gov.br/servicos/empregador/consultarloteeven" +
            "tos/WsConsultarLoteEventos.svc")]
        public string WebServices_WsConsultarLoteEventos_ServicoConsultarLoteEventos {
            get {
                return ((string)(this["WebServices_WsConsultarLoteEventos_ServicoConsultarLoteEventos"]));
            }
        }
    }
}
